"""add tenants table

Revision ID: 058ad3ce89a0
Revises: 1afabfc6bd2a
Create Date: 2026-05-02 10:22:50.815673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '058ad3ce89a0'
down_revision: Union[str, Sequence[str], None] = '1afabfc6bd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_peer_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.alter_column(
        'peers',
        'public_key',
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=88),
        existing_nullable=False,
    )
    op.alter_column(
        'peers',
        'allowed_ips',
        existing_type=sa.VARCHAR(length=512),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.drop_index(op.f('ix_peers_user_id'), table_name='peers')
    op.create_index(op.f('ix_peers_id'), 'peers', ['id'], unique=False)
    op.drop_constraint(op.f('peers_user_id_fkey'), 'peers', type_='foreignkey')
    op.create_foreign_key(None, 'peers', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)

    # tenants table (added manually)
    op.create_table(
        'tenants',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('slug', sa.String(length=64), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.UniqueConstraint('slug', name='uq_tenants_slug'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_constraint(None, 'peers', type_='foreignkey')
    op.create_foreign_key(op.f('peers_user_id_fkey'), 'peers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_peers_id'), table_name='peers')
    op.create_index(op.f('ix_peers_user_id'), 'peers', ['user_id'], unique=False)
    op.alter_column('peers', 'allowed_ips',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('peers', 'public_key',
               existing_type=sa.String(length=88),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('peer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['peer_id'], ['peers.id'], name=op.f('audit_logs_peer_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('audit_logs_resource_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('idx_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_timestamp'), 'audit_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_audit_logs_peer_id'), 'audit_logs', ['peer_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
