"""add_groups_resources_policies

Revision ID: 1afabfc6bd2a
Revises: 626a6923ea14
Create Date: 2026-04-22 16:02:37.681067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1afabfc6bd2a'
down_revision: Union[str, Sequence[str], None] = '626a6923ea14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
