"""add_revoked_at_to_peers

Revision ID: f2876d8ebb6c
Revises: b97dc959c190
Create Date: 2026-06-23 13:15:09.514399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2876d8ebb6c'
down_revision: Union[str, Sequence[str], None] = 'b97dc959c190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('peers', 'provisioning_status',
               existing_type=postgresql.ENUM('pending', 'provisioned', 'error', 'removed', 'pending_revoke', name='provisioningstatus'),
               server_default='pending',
               existing_nullable=False)
    op.drop_constraint(op.f('peers_public_key_key'), 'peers', type_='unique')
    op.drop_constraint(op.f('peers_vpn_ip_key'), 'peers', type_='unique')
    op.create_index(op.f('ix_peers_provisioning_status'), 'peers', ['provisioning_status'], unique=False)
    op.create_index(op.f('ix_peers_public_key'), 'peers', ['public_key'], unique=True)
    op.create_index(op.f('ix_peers_user_id'), 'peers', ['user_id'], unique=False)
    op.create_index(op.f('ix_peers_vpn_ip'), 'peers', ['vpn_ip'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peers_vpn_ip'), table_name='peers')
    op.drop_index(op.f('ix_peers_user_id'), table_name='peers')
    op.drop_index(op.f('ix_peers_public_key'), table_name='peers')
    op.drop_index(op.f('ix_peers_provisioning_status'), table_name='peers')
    op.create_unique_constraint(op.f('peers_vpn_ip_key'), 'peers', ['vpn_ip'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('peers_public_key_key'), 'peers', ['public_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('peers', 'provisioning_status',
               existing_type=postgresql.ENUM('pending', 'provisioned', 'error', 'removed', 'pending_revoke', name='provisioningstatus'),
               server_default=None,
               existing_nullable=False)
    op.drop_column('peers', 'revoked_at')
    # ### end Alembic commands ###
